Examples and brief docs for oci-factory's reusable workflows
canonical/rocks-toolbox pull request #21
Opened 2024-12-02 11:25 UTC by clay-lake

Features included in this PR:
- Introduction and brief documentation for oci-factory's reusable workflows.
- Various samples on how to integrate Build-Rock and Test-Rock workflows.

2024-12-03 13:53 UTC, cjdcordeiro commented on oci_factory_workflows/REAME.md
this would be nice within the oci-factory repo docs

2024-12-05 16:01 UTC, cjdcordeiro requested changes
LGTM. Can we rename the GH workflows to have some form of identifier? Since this is a sort of catch-all repo, it's safer to name things as explicitly as possible, especially when the files may be mixed with others from different contexts.

So, what about adding a prefix like "oci_factory"? And the same for the workflow `name`s

2024-12-06 14:47 UTC, clay-lake commented on .github/workflows/build_and_test_eicar_rock.yaml
> +name: Build and Test EICAR Rock
```suggestion
# Warning: This workflow is designed to fail. When merging in a PR, pushing an empty commit will bypass checks and allow the PR to be merged.
name: Build and Test EICAR Rock
```

2024-12-06 14:48 UTC, clay-lake commented on .github/workflows/test_external_rock.yaml
> +name: Test External Rock
```suggestion
# Warning: This workflow is designed to fail. When merging in a PR, pushing an empty commit will bypass checks and allow the PR to be merged.
name: Test External Rock
```

2024-12-06 16:49 UTC, cjdcordeiro approved these changes
great thanks

2024-12-06 16:51 UTC, cjdcordeiro commented
Can you squash and sign? The branch protection doesn't allow me to merge without signing the commits

2024-12-07 08:59 UTC, zhijie-yang approved these changes
LGTM, thanks.

2024-12-13 15:16 UTC, merged